services:
<<<<<<< HEAD
=======
  # БД
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
  mysql:
    image: mysql:8.0
    container_name: micro-mess-mysql
    environment:
<<<<<<< HEAD
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
=======
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
      - MYSQL_DATABASE=micro
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
<<<<<<< HEAD
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

=======
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    restart: unless-stopped
 
  # AUTH-SERVICE
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
<<<<<<< HEAD
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=micro
=======
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservices-net

<<<<<<< HEAD
=======
  # USER-SERVICE 
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
<<<<<<< HEAD
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=micro
=======
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservices-net

<<<<<<< HEAD
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=micro
      - PORT=8083
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./chat-service:/app
      - go-mod-cache:/go/pkg/mod
    networks:
      - microservices-net

=======
      ## GATEWAY
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
<<<<<<< HEAD
      - ./frontend:/app/frontend:ro
    depends_on:
      - auth-service
      - user-service
      - chat-service  # ← ДОБАВЛЕНО
=======
    - ./frontend:/app/frontend  
    depends_on:
      - auth-service
      - user-service
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
    networks:
      - microservices-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
<<<<<<< HEAD
  mysql-data:
  go-mod-cache:
=======
  mysql-data:
>>>>>>> 504fd3e5a511bf68e5f35cecc92e257c0bb17d56
